pipeline {

    agent any

    environment {

        IMAGE_NAME = "my-app"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Install Dependencies') {

            steps {

                sh 'npm install'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'npm test'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh '''
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                '''
            }

        }

        stage('Deploy Kubernetes') {

            steps {

                sh '''

                kubectl apply -f k8s/deployment.yaml

                '''

            }

        }

        stage('Verify') {

            steps {

                sh '''

                kubectl get pods

                kubectl get svc

                '''

            }

        }

    }

    post {

        success {

            echo 'Deployment Successful'

        }

        failure {

            echo 'Deployment Failed'

        }

    }

}